name: Build & Deploy Vue App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Lấy source code
      uses: actions/checkout@v3

    - name: Cài Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cài dependencies
      run: npm install

    - name: Build Vue project
      run: npm run build

    - name: Deploy lên GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
